
[GLOBAL]
pants_version="2.13.0"

use_deprecated_directory_cli_args_semantics = false
use_deprecated_pex_binary_run_semantics = false

pythonpath = ["%(buildroot)s/pants_plugins"]
plugins = ['sendwave-pants-docker==1.1.0']


backend_packages = [
                 "pants.backend.plugin_development",
                 "pants.backend.python",
                 "pants.backend.python.lint.black",
                 "pants.backend.python.lint.isort" ,
                 "sendwave.pants_node",
                 "sendwave.pants_docker"
                 ]

[source]
root_patterns = ["/pants_plugins", "/", "/test_webpack"]

[node]
use_nvm = true

[python-bootstrap]
search_path = ["<PYENV>"]

[python]
tailor_pex_binary_targets = false
interpreter_constraints = [">=3.8"]


[anonymous-telemetry]
enabled = true
repo_id = "BB6CBFC17A66FAB02E3FA88C13113D25"

[sendwave-docker]
report_progress = true